# Generated by Django 2.2.9 on 2020-08-07 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color_tag',
            name='ppt_tag',
        ),
        migrations.RemoveField(
            model_name='recent',
            name='ppt_recent',
        ),
        migrations.AddField(
            model_name='recent',
            name='recent_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recent',
            name='user_num',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Recent')),
                ('template_recent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_recent', to='main.Powerpoint')),
            ],
        ),
        migrations.CreateModel(
            name='PPT_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Color_tag')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Powerpoint')),
            ],
        ),
    ]
