# Generated by Django 2.2.9 on 2020-08-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200808_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='download_list',
            name='download_id',
        ),
    ]
