# Generated by Django 2.2.9 on 2020-08-11 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_remove_download_list_download_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_num', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='download_item',
            name='download',
        ),
        migrations.RemoveField(
            model_name='download_item',
            name='templates',
        ),
        migrations.RemoveField(
            model_name='download_list',
            name='user_num',
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ppt_tag',
            name='ppt_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ColorTag'),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_id',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Color_tag',
        ),
        migrations.DeleteModel(
            name='Download_Item',
        ),
        migrations.DeleteModel(
            name='Download_List',
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='download',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DownloadList'),
        ),
        migrations.AddField(
            model_name='downloaditem',
            name='templates',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='main.Powerpoint'),
        ),
    ]
