# Generated by Django 2.2.9 on 2020-08-11 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200811_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppt_tag',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Powerpoint'),
        ),
    ]
