# Generated by Django 2.1.15 on 2020-08-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200807_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color_tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(db_index=True, max_length=100)),
                ('ppt_tag', models.ManyToManyField(to='main.Powerpoint')),
            ],
        ),
    ]
