# Generated by Django 2.1.15 on 2020-08-07 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_color_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Powerpoint'),
        ),
    ]
