# Generated by Django 2.2.9 on 2020-08-11 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200811_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppt_tag',
            name='ppt_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ColorTag'),
        ),
    ]
