# Generated by Django 2.2.9 on 2020-08-11 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200811_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadlist',
            name='user_id',
        ),
    ]
