# Generated by Django 2.2.9 on 2020-08-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_downloadlist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadlist',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
