# Generated by Django 2.1.15 on 2020-08-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200807_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ppt_cart',
        ),
    ]
