# Generated by Django 2.2.9 on 2020-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_downloadlist_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recent',
            name='recent_id',
            field=models.IntegerField(null=True),
        ),
    ]
