# Generated by Django 2.1.15 on 2020-08-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_cart_ppt_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerpoint',
            options={},
        ),
    ]
