# Generated by Django 2.1.15 on 2020-08-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200807_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerpoint',
            name='color_tag',
        ),
        migrations.AlterField(
            model_name='powerpoint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
