# Generated by Django 2.2.9 on 2020-08-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200807_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PptbizcamReal',
        ),
    ]
