# Generated by Django 2.2.9 on 2020-08-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200811_1901'),
        ('main', '0009_auto_20200811_1055'),
    ]

    operations = [
    ]
