# Generated by Django 2.2.9 on 2020-08-12 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_merge_20200812_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppt_tag',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='powerpoint', to='main.Powerpoint'),
        ),
    ]
