# Generated by Django 2.2.9 on 2020-08-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_pptbizcamreal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='main.Powerpoint'),
        ),
    ]
