# Generated by Django 2.2.9 on 2020-08-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200812_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerpoint',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
