# Generated by Django 2.2.9 on 2020-08-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_powerpoint_download_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Count',
        ),
    ]
